---
permalink: concept-configure-snapmanager-for-hyper-v-for-failover.html 
sidebar: sidebar 
keywords: enable, snapmanager, hyper-v, implementation, disaster, recovery, primary, secondary, host, powershell, failover, configure, configuring 
summary: 要完全启用SnapManager for Hyper-V实施以实现灾难恢复、您必须确保主主机和二级主机具有相同的配置、并且知道您只能使用PowerShell执行灾难恢复。 
---
= 为Hyper-V配置SnapManager 以实现故障转移
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
要完全启用SnapManager for Hyper-V实施以实现灾难恢复、您必须确保主主机和二级主机具有相同的配置、并且知道您只能使用PowerShell执行灾难恢复。

以下类型的设置支持灾难恢复：

* 独立主主机和独立二级Hyper-V主机
* 集群模式主Hyper-V主机和二级Hyper-V主机
* 主Hyper-V主机和二级Hyper-V主机上的集群共享卷(CSV)


例如、主主机上的集群虚拟机(VM)必须作为集群VM进行恢复、专用(独立) VM必须作为专用VM进行恢复、CSV VM必须作为CSV VM进行恢复。

二级主机上的LUN应与主主机上的LUN连接方式相同。也就是说、主主机和二级主机上的LUN类型(专用、共享或CSV)和驱动器盘符、挂载点或CSV重新解析点应相同。如果将SAN还原操作设置为备用路径位置、则可以在二级位置为LUN还原操作指定不同的驱动器盘符。


NOTE: 支持驱动器号或CSV以及卷挂载点。

以下示例显示了基本的灾难恢复设置：

* 站点A (主站点)包含存储系统和独立Hyper-V主机系统或Hyper-V主机集群。
+
在这些主机上运行的VM位于Data ONTAP 存储上。

* 站点B (二级)包含存储系统和Hyper-V主机或集群(与主站点相同)。
* SnapDrive for Windows和SnapManager for Hyper-V同时安装在站点A和B上
* SnapMirror关系将从站点A初始化到站点B
* 在站点A上、添加到SnapManager for Hyper-V中的Hyper-V主机或集群以及VM均使用SnapManager for Hyper-V进行备份
+
检查备份后更新SnapMirror的策略。每次备份后、二级站点都会使用VM的新Snapshot副本和SnapInfo副本进行更新。


