---
permalink: concept-data-management-concepts.html 
sidebar: sidebar 
keywords: snapmanager, hyper-v, dataset, policies, policy, enable, group, virtual, machine, apply, rule, retention, data, management, concept 
summary: SnapManager for Hyper-V可使用数据集和策略对虚拟机进行分组、然后将规则应用于这些组以控制其行为。 
---
= 数据管理概念
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapManager for Hyper-V可使用数据集和策略对虚拟机进行分组、然后将规则应用于这些组以控制其行为。在使用SnapManager for Hyper-V计划备份并指定备份保留策略的情况下、此信息非常有用。

* *数据集*
+
数据集是一组虚拟机(VM)、可用于使用保留、计划和复制策略保护数据。您可以使用数据集对具有相同保护要求的虚拟机进行分组。一个VM可以是多个数据集的一部分。

* * Hyper-V父主机*
+
Hyper-V父主机是启用了Hyper-V角色的物理服务器。包含虚拟机的主机将添加到SnapManager for Hyper-V中以进行保护和恢复。必须在每个Hyper-V父主机上安装并运行SnapManager for Hyper-V。

* *未受保护的资源*
+
未受保护的资源是指不属于任何数据集的虚拟机。您可以通过将这些资源添加到数据集来保护这些资源。

* *虚拟机*
+
在Hyper-V父主机上运行的虚拟机表示物理机、具有自己的操作系统、应用程序和硬件。

+
SnapManager for Hyper-V会跟踪虚拟机的全局唯一标识符(GUID)、而不是虚拟机名称。如果删除了受SnapManager for Hyper-V保护的虚拟机、然后创建了一个同名的其他虚拟机、则新虚拟机将不受保护、因为它具有不同的GUID。

* *管理控制台*
+
管理控制台是指安装了SnapManager for Hyper-V并作为客户端运行的计算机。您可以使用管理控制台在远程Hyper-V父主机上远程管理SnapManager for Hyper-V操作。

* *计划策略*
+
计划策略会为特定时间分配备份作业、使您能够自动执行计划过程。您可以添加多个计划策略、这些策略适用于属于数据集成员的所有虚拟机。SnapManager for Hyper-V使用Windows计划程序创建计划的任务。

* *保留策略*
+
保留策略是您在SnapManager for Hyper-V中管理数据集备份保留的方式保留策略可根据备份副本的时间或数量确定数据集备份的保留时间。

+
您在保留策略中设置的限制可确保数据备份不会影响未来的存储容量。

+
您可以在SnapManager for Hyper-V中设置以下保留期限：

+
** 一小时
** 一天
** 一周
** 一个月
** 无限制





NOTE: 您可以为每个数据集指定一次保留期限。

选择删除数据集备份的频率后、您可以选择删除早于指定时间段的备份或超过最大总数的备份。

如果您的系统似乎保留了旧备份、请检查您的保留策略。要使保留策略触发Snapshot副本的删除、共享Snapshot副本的所有要备份的对象都必须满足备份删除标准。

* *复制策略*
+
复制策略可确定是否在成功执行备份操作后更新SnapMirror目标。SnapManager for Hyper-V仅支持基于卷的SnapMirror。在尝试执行SnapMirror更新之前、您必须在两个存储系统上配置SnapMirror关系。这对于源和目标都是必需的。



* 相关信息 *

https://library.netapp.com/ecm/ecm_download_file/ECMP1368826["《Data ONTAP 8.2 7-模式数据保护联机备份和恢复指南》"]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30049["NetApp 文档： SnapDrive for Windows （当前版本）"]
