---
permalink: reference_space_consumption_when_making_two_snapshot_copies_for_each_backup.html 
sidebar: sidebar 
keywords: space, consumption, snapshot, copies, copy, backup 
summary: 为每个备份创建两个Snapshot副本时占用的空间。 
---
= 为每个备份创建两个Snapshot副本时占用的空间
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* * 问题描述 *
+
对于包含Hyper-V对象的每个备份、都会创建两个Snapshot副本、这可能会导致对空间消耗的担忧。

+

NOTE: 这只是适用场景 应用程序一致的备份。

* * 发生原因 *
+
Microsoft Hyper-V VSS写入程序会在VM中创建VM和应用程序一致的备份副本、并将应用程序驻留在VHD上。为了创建软件一致的备份副本和虚拟机一致的备份副本、VSS会采用原生 自动恢复过程、从而将虚拟机设置为与软件Snapshot副本一致的状态。Hyper-V VSS写入程序会联系备份中的每个虚拟机、并创建软件一致的Snapshot副本。

+
创建Snapshot副本后、父分区将为托管这些VM的整个磁盘(LUN)创建一个VSS Snapshot副本。创建父分区Snapshot副本后、VSS需要挂载先前创建的父分区、将每个VM回滚到软件一致的状态、并删除在创建软件Snapshot副本后对VM所做的任何更改。对VHD进行的这些修改必须永久保留。由于默认情况下这些Snapshot副本为只读副本、因此必须创建新的Snapshot副本以保留更新后的VHD副本。因此、将为卷创建第二个Snapshot副本。此Snapshot副本标有后缀*；backup*、是用于还原操作的备份副本。

* * 更正操作 *
+
这两个Snapshot副本被视为一对。当备份的保留期限结束时、两个Snapshot副本都会被删除。您不应手动删除第一个Snapshot副本、因为它对于还原操作是必需的。

+
Microsoft VSS仅支持在拥有集群共享卷(CSV)的主机上备份VM、因此CSV所有权会在节点之间移动、以便为集群中每个主机上的VM创建备份。

+
备份CSV时、SnapManager for Hyper-V会在集群中运行该CSV中的虚拟机的每个主机上创建两个Snapshot副本。这意味着、如果在一个CSV上备份15个VM、并且这些VM均匀分布在三个Hyper-V服务器上、则每个备份总共会有六个Snapshot副本。


