---
permalink: reference_requirements_for_manually_backing_up_a_dataset.html 
sidebar: sidebar 
keywords: backup, dataset, manual, first, name, describe, type, option, retention, policy, requirement 
summary: 要手动备份数据集、您必须先为数据集命名并进行说明、选择备份类型和选项、然后设置保留策略。 
---
= 手动备份数据集的要求
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
要手动备份数据集、您必须先为数据集命名并进行说明、选择备份类型和选项、然后设置保留策略。



== 备份名称和问题描述

您必须为备份分配一个名称和问题描述。

备份的默认命名约定为DatasetName_Timestamp。您可以更改备份名称中的所有内容、但时间戳除外、时间戳始终显示为备份名称的一部分。

备份名称和说明仅限于以下字符：

* a到z
* A到Z
* 0到9
* _(下划线)
* 连字符




== 策略选择

您必须确定要用于按需备份的策略。

您可以在备份向导中选择特定策略。您可以覆盖保留或复制策略以及与此策略关联的脚本、而无需更改此策略本身。

您还可以选择无、这样您无需创建任何策略即可按需进行备份。此选项将使用保留策略、复制策略和脚本的默认值。



== 保留值

您可以选择覆盖选定策略中指定的保留策略。如果执行此操作、则必须先确定要保留每小时、每天、每周、每月或无限制备份副本的最短时间、然后再将其删除。

您可以根据备份时间或指定数量来保留备份。例如、您可以保留10个最新备份、也可以删除15天之前的备份。



== 备份类型

您可以执行应用程序一致或崩溃一致的备份。



== 备份选项

您可以允许保存状态备份。

SnapManager for Hyper-V的默认行为是、如果一个或多个虚拟机无法联机备份、备份将失败。如果虚拟机处于已保存状态或已关闭、则无法执行联机备份。在某些情况下、虚拟机处于已保存状态或已关闭以进行维护、但备份仍必须继续、即使无法进行联机备份也是如此。为此、您可以将处于已保存状态的虚拟机移动或关闭到其他数据集、其中一个数据集的策略允许进行已保存状态备份。

您也可以通过选中允许已保存状态的VM备份复选框来修改现有策略。这样、SnapManager for Hyper-V便可在已保存状态下备份虚拟机。如果选择此选项、则在Hyper-V VSS写入程序以已保存状态备份虚拟机或对虚拟机执行脱机备份时、适用于Hyper-V的SnapManager 不会使备份失败。执行已保存状态或脱机备份可能会导致发生原因 停机。

通过分布式应用程序一致的备份功能、在从备份节点创建的一个硬件Snapshot副本中、可以使配对集群节点上运行的多个VM保持一致。在Windows故障转移集群中的多个节点上运行CSV 2.0 Windows卷的所有VM均支持此功能。



== SnapMirror备份中的二级存储

通过这些选项、您可以接受适用于SnapMirror关系中定义的二级存储的选项。您可以选择*备份后更新Snapmirror*。在存储标签选项窗格下、您可以选择*备份后更新SnapVault *。如果选择*备份后更新SnapVault *、则必须从下拉菜单中选择存储标签或输入自定义标签。



== 备份脚本

您可以覆盖选定策略中指定的脚本选项。

除非您在脚本中指定了特定主机、否则这些脚本将在所有数据集成员主机上运行。

* 相关信息 *

http://technet.microsoft.com/library/cc753637(WS.10).aspx["Microsoft TechNet：Hyper-V"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-buvault/home.html["《使用 SnapVault 备份 ONTAP 9 卷快速指南》"]
