---
permalink: reference_requirements_for_adding_a_hyper_v_parent_host_or_host_cluster.html 
sidebar: sidebar 
keywords: configuration, information, available, parent, host, cluster, snapmanager, hyper-v 
summary: 在将父主机或主机集群添加到SnapManager for Hyper-V之前、您必须具有所有必要的配置信息 
---
= 添加Hyper-V父主机或主机集群的要求
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在将父主机或主机集群添加到SnapManager for Hyper-V之前、您必须具有所有必要的配置信息



== SnapManager for Hyper-V安装

要添加的Hyper-V主机上必须安装SnapManager for Hyper-V。

如果您未安装SnapManager for Hyper-V、系统将提示您运行远程主机安装向导。每个集群节点上必须安装相同版本的SnapManager for Hyper-V。



== 配置设置

必须为SnapManager for Hyper-V配置要添加的Hyper-V父主机

如果未为适用于Hyper-V的SnapManager 配置SnapInfo设置、报告目录设置和通知设置、则可以在添加主机后使用配置向导对其进行配置。

最初、*管理存储连接*选项卡为空。您可以从*管理存储连接*选项卡添加存储连接、但新添加的连接可从SnapDrive for Windows (SDW)传输协议设置(TPS)中查看。

您必须使用SnapManager for Hyper-V配置备份存储库和报告目录设置以添加和管理虚拟机通知设置为可选设置。



== 虚拟机和ONTAP LUN

与虚拟机关联的所有文件(包括配置文件、Snapshot副本文件位置和VHD)都必须驻留在ONTAP LUN上。

这是成功执行备份所必需的。


NOTE: 如果在创建虚拟机后将虚拟机Snapshot文件位置更改为其他ONTAP LUN、则应在使用适用于Hyper-V的SnapManager 创建备份之前、使用Hyper-V Manager至少创建一个虚拟机Snapshot副本如果更改Snapshot副本文件位置、并且在创建备份之前未创建虚拟机Snapshot副本、则备份操作可能会失败。



== 专用虚拟机和集群虚拟机

虚拟机可以是专用虚拟机、也可以是集群的一部分。

如果添加单个主机、则SnapManager for Hyper-V将管理该主机上的专用虚拟机。如果添加主机集群、则SnapManager for Hyper-V将管理主机集群上的共享虚拟机。位于SAN和NAS上属于同一主机集群的虚拟机不应位于同一数据集中。如果将这些类型的资源添加到单个数据集、则发生原因 数据集备份可能会失败。

对于应用程序一致的备份、当集群虚拟机在集群的不同节点上运行时、完成集群虚拟机的数据集备份需要较长时间。当虚拟机在不同节点上运行时、集群中的每个节点都需要单独的备份操作。如果所有虚拟机都在同一节点上运行、则只需要执行一次备份操作、从而加快备份速度。



== 虚拟机数量

如果Hyper-V主机或主机集群中的虚拟机数超过1、000个、则必须增加Hyper-V Cache Manager的SnapMgrServiceHost.exe配置文件中的maximumElementsInCacheBeforeScavenging属性的值。此值应大于或等于在独立主机或集群上运行的Hyper-V主机数。应在集群的每个节点上更改此值、并且在更改此值后、必须重新启动适用于Hyper-V的SnapManager 服务。您必须使用文本编辑器手动编辑SnapMgrServiceHost.exe配置文件。

[listing]
----
<cacheManagers>
…
      <add name="HyperV Cache Manager"
                        type="Microsoft.Practices.EnterpriseLibrary.Caching.CacheManager,
                           Microsoft.Practices.EnterpriseLibrary.Caching"
                        expirationPollFrequencyInSeconds="60"
                        maximumElementsInCacheBeforeScavenging="1200"
                        numberToRemoveWhenScavenging="10"
                        backingStoreName="inMemory" />
…
</cacheManagers>
----


== SnapManager for Hyper-V服务帐户要求

使用SnapManager for Hyper-V管理Hyper-V主机集群时、SnapManager for Hyper-V和SnapDrive for Windows服务帐户必须是在服务器上具有本地管理员权限的域用户帐户。

SnapManager for Hyper-V应用程序一致的备份在虚拟机运行的集群节点上运行。如果虚拟机使用的集群共享卷(CSV)不属于同一节点、则在Hyper-V SnapManager 服务使用本地系统帐户时、虚拟机备份可能会失败(即使该帐户具有管理员权限)。在这种情况下、SnapManager for Hyper-V无法检测到虚拟机文件驻留在CSV上、从而导致备份失败。


NOTE: 要使集群模式Data ONTAP SMB 3.0持续可用性(CA)共享上存储的虚拟机的远程卷影复制服务(VSS)操作正常运行、 您必须为SnapDrive for Windows服务帐户的共享授予完全控制权限、并为SnapManager for Hyper-V Web服务帐户授予最低读取级别访问权限。

* 相关信息 *

http://technet.microsoft.com/library/cc753637(WS.10).aspx["Microsoft TechNet：Hyper-V"]
