---
permalink: task-set-up-a-snapinfo-lun.html 
sidebar: sidebar 
keywords: add, snapinfo, lun, snapmanager, hyper-v, store, dataset, backup, metadata, reside, ontap, setting, up 
summary: 您必须在SnapManager for Hyper-V中添加SnapInfo LUN以存储数据集备份元数据。SnapInfo路径必须驻留在ONTAP LUN上、因为SnapManager for Hyper-V会在定期备份后对SnapInfo副本进行备份。 
---
= 设置SnapInfo LUN
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
您必须在SnapManager for Hyper-V中添加SnapInfo LUN以存储数据集备份元数据。SnapInfo路径必须驻留在ONTAP LUN上、因为SnapManager for Hyper-V会在定期备份后对SnapInfo副本进行备份。

如果您运行的是Windows Server 2012集群、则SnapInfo路径可以位于集群共享卷(CSV)上。如果管理专用虚拟机、则SnapInfo位置必须位于专用ONTAP LUN上。如果管理共享虚拟机、则SnapInfo位置必须位于共享ONTAP LUN上。

.步骤
. 使用适用于Windows的SnapDrive 创建新的共享磁盘。
+
.. 如果提供了选择Microsoft集群服务组的选项、请选择*创建新集群组*选项
.. 将组命名为`smhv_snapinfo`并完成此过程。


. 打开Windows故障转移集群(WFC)并验证新组是否联机。
. 在集群中的每个节点上安装SnapManager for Hyper-V。
. 运行*配置*向导并将SnapInfo配置设置应用于集群中的所有节点。
+
.. 选择一个主机。
.. 从*导航*窗格中、单击菜单：保护[主机]。
.. 从操作窗格中、运行*配置*向导。
.. 将SnapInfo设置应用于新创建的LUN。




运行配置向导时、SnapInfo配置设置将复制到集群中的所有节点。* 相关信息 *

xref:reference-error-snapdrive-sddiscoveryfilesystemlistinfo-response-is-null.adoc[错误：SnapDrive SDDiscoveryFileSystemListInfo响应为空]
